import type { CardDefinition } from './types';

/**
 * 断罪之刃 —— 低费高频的多段攻击堆余烬，再把锋锐一次花掉。
 * 攻击牌极多、防御薄弱；爆发来自「多段 × 锋锐」，所以怕被拖长。
 */
export const DECK_BLADE: CardDefinition[] = [
  // ── 残烬 · cinder ─────────────────────────────────────────────── 基础、直接、多为 1 费
  { id: 'blade-01', name: '割线', deck: 'blade', tier: 'cinder', cost: 1, type: 'attack',
    text: '造成 6 点伤害，获得 1 层余烬。', keywords: ['ember'],
    lore: '一线划过，命与夜在同一瞬断开。' },
  { id: 'blade-02', name: '双刃', deck: 'blade', tier: 'cinder', cost: 1, type: 'attack',
    text: '造成 3 点伤害 2 次，获得 1 层余烬。', keywords: ['ember'],
    lore: '两刃同出，总有一刃认得血的味道。' },
  { id: 'blade-03', name: '掩刃', deck: 'blade', tier: 'cinder', cost: 1, type: 'skill',
    text: '获得 5 点格挡。', keywords: [],
    lore: '把刀横在身前，整片夜都慢了。' },
  { id: 'blade-04', name: '错锋', deck: 'blade', tier: 'cinder', cost: 0, type: 'attack',
    text: '造成 3 点伤害。', keywords: [],
    lore: '刀还没收尽，第二刀已经到了。' },
  { id: 'blade-05', name: '拾烬', deck: 'blade', tier: 'cinder', cost: 0, type: 'skill',
    text: '获得 1 层余烬。', keywords: ['ember'],
    lore: '火熄了很久，灰里仍旧留着红。' },
  { id: 'blade-06', name: '划痕', deck: 'blade', tier: 'cinder', cost: 1, type: 'attack',
    text: '造成 7 点伤害。', keywords: [],
    lore: '夜裂开一道白，随即又慢慢合上。' },
  { id: 'blade-07', name: '退刃', deck: 'blade', tier: 'cinder', cost: 1, type: 'skill',
    text: '获得 4 点格挡，获得 1 层余烬。', keywords: ['ember'],
    lore: '退开半步，只为看清那道伤口。' },

  // ── 微光 · glimmer ────────────────────────────────────────────── 牌组骨架
  { id: 'blade-08', name: '连斩', deck: 'blade', tier: 'glimmer', cost: 2, type: 'attack',
    text: '造成 4 点伤害 2 次，获得 1 层余烬。', keywords: ['ember'],
    lore: '刀势不停，血便来不及落在地上。' },
  { id: 'blade-09', name: '攒烬', deck: 'blade', tier: 'glimmer', cost: 1, type: 'skill',
    text: '获得 2 层余烬。', keywords: ['ember'],
    lore: '把每一粒红都收进袖中，等它长大。' },
  { id: 'blade-10', name: '三叠', deck: 'blade', tier: 'glimmer', cost: 2, type: 'attack',
    text: '造成 3 点伤害 3 次。', keywords: [],
    lore: '三刀叠在一处，落在身上只算一刀。' },
  { id: 'blade-11', name: '卸锋', deck: 'blade', tier: 'glimmer', cost: 1, type: 'skill',
    text: '获得 5 点格挡。消耗 1 层锋锐，再获得 3 点格挡。', keywords: ['edge'], bridge: 'bone',
    lore: '把锋芒折回鞘里，换来一层甲。' },
  { id: 'blade-12', name: '掠火', deck: 'blade', tier: 'glimmer', cost: 1, type: 'attack',
    text: '造成 5 点伤害。若目标已被灼烧，额外造成 3 点伤害。', keywords: ['scorch'], bridge: 'flame',
    lore: '借别人的火，烧别人身上的甲。' },
  { id: 'blade-13', name: '循隙', deck: 'blade', tier: 'glimmer', cost: 1, type: 'attack',
    text: '造成 4 点伤害，获得 1 层余烬。若本回合已打出过攻击牌，额外获得 1 层余烬。', keywords: ['ember'],
    lore: '第一刀开出缝，第二刀循缝而入。' },
  { id: 'blade-14', name: '疾影', deck: 'blade', tier: 'glimmer', cost: 0, type: 'attack',
    text: '造成 2 点伤害 2 次。', keywords: [],
    lore: '快得连自己的影子都跟不上。' },
  { id: 'blade-15', name: '守烬', deck: 'blade', tier: 'glimmer', cost: 2, type: 'skill',
    text: '获得 9 点格挡，获得 1 层余烬。', keywords: ['ember'],
    lore: '守着那点红，像守着一整座城。' },

  // ── 明焰 · blaze ──────────────────────────────────────────────── 有明确特色的中坚
  { id: 'blade-16', name: '断罪', deck: 'blade', tier: 'blaze', cost: 2, type: 'attack',
    text: '造成 8 点伤害，获得 1 层余烬。', keywords: ['ember'],
    lore: '判决落下的时候，夜里没有回声。' },
  { id: 'blade-17', name: '刃雨', deck: 'blade', tier: 'blaze', cost: 2, type: 'attack',
    text: '造成 2 点伤害 4 次，获得 1 层余烬。', keywords: ['ember'],
    lore: '刀落如雨，雨里没有一个人撑伞。' },
  { id: 'blade-18', name: '淬刃', deck: 'blade', tier: 'blaze', cost: 2, type: 'power',
    text: '每回合你首次打出攻击牌时，该牌额外造成 3 点伤害。', keywords: [],
    lore: '刀要在血里淬过一遍，才算开刃。' },
  { id: 'blade-19', name: '裂甲', deck: 'blade', tier: 'blaze', cost: 2, type: 'attack',
    text: '造成 7 点伤害。消耗 1 层锋锐，额外造成 4 点伤害。', keywords: ['edge'], bridge: 'bone',
    lore: '甲再厚，也厚不过一把刀的决心。' },
  { id: 'blade-20', name: '浸血', deck: 'blade', tier: 'blaze', cost: 2, type: 'attack',
    text: '造成 6 点伤害，获得 2 层余烬。', keywords: ['ember'],
    lore: '刃饮下的血，从不肯吐还给谁。' },
  { id: 'blade-21', name: '逆守', deck: 'blade', tier: 'blaze', cost: 2, type: 'skill',
    text: '获得 10 点格挡。若你本回合已打出过攻击牌，获得 1 层余烬。', keywords: ['ember'],
    lore: '守到极处，剩下的便是反手一刀。' },

  // ── 长明 · everburning ────────────────────────────────────────── 强力、有构筑指向
  { id: 'blade-22', name: '万刃', deck: 'blade', tier: 'everburning', cost: 3, type: 'attack',
    text: '造成 4 点伤害 4 次。', keywords: [],
    lore: '万刃同出，只为换来同一个结局。' },
  { id: 'blade-23', name: '殉火', deck: 'blade', tier: 'everburning', cost: 2, type: 'attack',
    text: '造成 10 点伤害，获得 2 层余烬。', keywords: ['ember'],
    lore: '把自己也丢进火里，才算够亮。' },
  { id: 'blade-24', name: '长夜', deck: 'blade', tier: 'everburning', cost: 2, type: 'skill',
    text: '获得 12 点格挡，获得 1 层余烬。', keywords: ['ember'],
    lore: '夜再长，也长不过胸口的这口气。' },
  { id: 'blade-25', name: '断念', deck: 'blade', tier: 'everburning', cost: 2, type: 'attack',
    text: '造成 6 点伤害。消耗至多 3 层锋锐，每层额外造成 3 点伤害。', keywords: ['edge'], bridge: 'bone',
    lore: '不再回头的人，刀落下去最重。' },
  { id: 'blade-26', name: '不熄', deck: 'blade', tier: 'everburning', cost: 3, type: 'rite',
    text: '每回合结束时，若你本回合打出过至少 2 张攻击牌，获得 2 层余烬。', keywords: ['ember'],
    lore: '谁也没看见它灭，它就一直烧着。' },

  // ── 星陨 · starfall ───────────────────────────────────────────── 招牌
  { id: 'blade-27', name: '烬爆', deck: 'blade', tier: 'starfall', cost: 3, type: 'attack',
    text: '消耗所有余烬，每层对目标造成 3 点伤害。', keywords: ['ember'], bridge: 'flame',
    lore: '所有没烧完的，今夜一起烧完。' },
  { id: 'blade-28', name: '千刃', deck: 'blade', tier: 'starfall', cost: 3, type: 'attack',
    text: '造成 2 点伤害 8 次，获得 2 层余烬。', keywords: ['ember'],
    lore: '刀刃数不清的时候，夜也数不清。' },
];
