import type { CardDefinition } from './types';

/**
 * 断罪之刃 —— 用 0~1 费的小段攻击把出牌数堆起来，命中次数换余烬；
 * 中后期再把攒下的锋锐一次花掉，让每一次命中都变重。攻击牌最多、防御最薄，怕被拖长。
 */
export const DECK_BLADE: CardDefinition[] = [
  // ── 残烬 · cinder ────────────────────────────────────────────── 0~1 费，一个效果，七张七个形状
  { id: 'blade-01', name: '割线', deck: 'blade', tier: 'cinder', cost: 1, type: 'attack', pattern: 'basic-strike',
    text: '造成 7 点伤害。', keywords: [],
    lore: '一线划过，命与夜在同一瞬断开。' },
  { id: 'blade-02', name: '双刃', deck: 'blade', tier: 'cinder', cost: 0, type: 'attack', pattern: 'multi-hit',
    text: '造成 3 点伤害 2 次。', keywords: [],
    lore: '两刃同出，总有一刃认得血的味道。' },
  { id: 'blade-03', name: '拾烬', deck: 'blade', tier: 'cinder', cost: 0, type: 'skill', pattern: 'resource-build',
    text: '获得 2 层余烬。', keywords: ['ember'],
    lore: '火熄了很久，灰里仍旧留着一点红。' },
  { id: 'blade-04', name: '掩刃', deck: 'blade', tier: 'cinder', cost: 1, type: 'skill', pattern: 'block-basic',
    text: '获得 6 点格挡。', keywords: [],
    lore: '把刀横在身前，整片夜都慢了下来。' },
  { id: 'blade-05', name: '试锋', deck: 'blade', tier: 'cinder', cost: 1, type: 'attack', pattern: 'sacrifice',
    text: '祭火：失去 3 点生命。造成 9 点伤害。', keywords: ['sacrifice'],
    lore: '割开自己的手，只为试出刀的深浅。' },
  { id: 'blade-06', name: '换手', deck: 'blade', tier: 'cinder', cost: 1, type: 'skill', pattern: 'discard',
    text: '流转：弃 1 张牌，然后抽 2 张牌。', keywords: ['cycle'],
    lore: '旧牌换新牌，夜也换了一种打法。' },
  { id: 'blade-07', name: '循隙', deck: 'blade', tier: 'cinder', cost: 0, type: 'attack', pattern: 'conditional-strike',
    text: '空明：若你的手牌为空，造成 9 点伤害。', keywords: ['empty'],
    lore: '手一空，刀反而知道该往哪里去。' },

  // ── 微光 · glimmer ───────────────────────────────────────────── 牌组骨架：余烬引擎、多段、第一次借外力
  { id: 'blade-08', name: '攒烬', deck: 'blade', tier: 'glimmer', cost: 1, type: 'skill', pattern: 'resource-build',
    text: '本回合内，你每次攻击命中时获得 1 层余烬。', keywords: ['ember'],
    lore: '把每一粒红都收进袖中，等它长大。' },
  { id: 'blade-09', name: '三叠', deck: 'blade', tier: 'glimmer', cost: 1, type: 'attack', pattern: 'multi-hit',
    text: '造成 2 点伤害 3 次。连缀：本回合第 3 张牌起改为 4 次。', keywords: ['chain'],
    lore: '三刀叠在一处，落在身上只算一刀。' },
  { id: 'blade-10', name: '折返', deck: 'blade', tier: 'glimmer', cost: 1, type: 'skill', pattern: 'recycle',
    text: '返照：把本回合打出的一张攻击牌退回手牌，它本回合费用为 0。', keywords: ['rewind'],
    lore: '刀回来了，像从没离开过你的手。' },
  { id: 'blade-11', name: '卸锋', deck: 'blade', tier: 'glimmer', cost: 1, type: 'skill', pattern: 'resource-convert',
    text: '消耗 2 层锋锐，获得 12 点格挡。', keywords: ['edge'], bridge: 'bone',
    lore: '把锋芒折回鞘里，换来一层甲。' },
  { id: 'blade-12', name: '掠火', deck: 'blade', tier: 'glimmer', cost: 1, type: 'attack', pattern: 'conditional-strike',
    text: '造成 5 点伤害。若目标身上有灼烧，改为造成 12 点伤害。', keywords: ['scorch'], bridge: 'flame',
    lore: '借别人的火，烧别人身上的甲。' },
  { id: 'blade-13', name: '逐影', deck: 'blade', tier: 'glimmer', cost: 1, type: 'attack', pattern: 'copy',
    text: '造成 5 点伤害。回响：把这张牌的一个弱化复制品加入手牌。', keywords: ['echo'],
    lore: '影子比人先一步到了下一个位置。' },
  { id: 'blade-14', name: '淬刃', deck: 'blade', tier: 'glimmer', cost: 2, type: 'power', pattern: 'ramp',
    text: '每回合你首次打出攻击牌时，它额外造成 3 点伤害，你获得 1 层余烬。', keywords: ['ember'],
    lore: '刀要在血里淬过一遍，才算开刃。' },
  { id: 'blade-15', name: '回鞘', deck: 'blade', tier: 'glimmer', cost: 1, type: 'skill', pattern: 'recycle',
    text: '拾回：从弃牌堆取回一张攻击牌。', keywords: ['reclaim'],
    lore: '收回去的那把刀，仍旧认得你的手。' },

  // ── 明焰 · blaze ─────────────────────────────────────────────── 有明确轴线的中坚
  { id: 'blade-16', name: '断罪', deck: 'blade', tier: 'blaze', cost: 2, type: 'attack', pattern: 'execute',
    text: '造成 6 点伤害。目标每失去 10% 生命，这张牌就多造成 2 点伤害。', keywords: [],
    lore: '判决落下的时候，夜里没有回声。' },
  { id: 'blade-17', name: '刃雨', deck: 'blade', tier: 'blaze', cost: 2, type: 'attack', pattern: 'aoe',
    text: '对所有敌人造成 4 点伤害 2 次，每命中一个敌人你获得 1 层余烬。', keywords: ['ember'],
    lore: '刀落如雨，雨里没有一个人撑伞。' },
  { id: 'blade-18', name: '刻痕', deck: 'blade', tier: 'blaze', cost: 1, type: 'attack', pattern: 'debuff',
    text: '造成 4 点伤害并烙印目标：你对被烙印的敌人造成的伤害 +3。', keywords: ['mark'],
    lore: '刻在刃上的名字，一个也逃不掉。' },
  { id: 'blade-19', name: '裂甲', deck: 'blade', tier: 'blaze', cost: 2, type: 'attack', pattern: 'resource-spend',
    text: '造成 7 点伤害。消耗至多 3 层锋锐，每层额外造成 4 点伤害。', keywords: ['edge'], bridge: 'bone',
    lore: '甲再厚，也厚不过一把刀的决心。' },
  { id: 'blade-20', name: '借焰', deck: 'blade', tier: 'blaze', cost: 1, type: 'attack', pattern: 'dot-convert',
    text: '造成 5 点伤害。引爆：消耗目标身上全部灼烧，每层使你获得 1 层余烬。', keywords: ['detonate', 'scorch', 'ember'], bridge: 'flame',
    lore: '别人点的火，最后由你来收场。' },
  { id: 'blade-21', name: '逆守', deck: 'blade', tier: 'blaze', cost: 1, type: 'skill', pattern: 'retaliate',
    text: '获得 7 点格挡。反震：本回合内每次被攻击时，对攻击者造成 4 点伤害。', keywords: ['retaliate'],
    lore: '守到极处，剩下的便是反手一刀。' },

  // ── 长明 · everburning ────────────────────────────────────────── 需要铺垫的引擎与转化
  { id: 'blade-22', name: '万刃', deck: 'blade', tier: 'everburning', cost: 2, type: 'attack', pattern: 'multi-hit',
    text: '造成 3 点伤害。连缀：本回合你每打出过 1 张牌，就再造成 3 点伤害。', keywords: ['chain'],
    lore: '刃数不清的时候，夜也数不清。' },
  { id: 'blade-23', name: '断念', deck: 'blade', tier: 'everburning', cost: 1, type: 'attack', pattern: 'exhaust-payoff',
    text: '焚尽你手中的一张牌。造成 6 点伤害，本场每有 1 张已焚尽的牌就额外造成 4 点伤害。', keywords: ['exhaust'],
    lore: '不再回头的人，刀落下去最重。' },
  { id: 'blade-24', name: '不熄', deck: 'blade', tier: 'everburning', cost: 2, type: 'rite', pattern: 'upgrade',
    text: '刻印：本场战斗永久强化牌组中的一张攻击牌，使它的每次命中 +3 伤害。', keywords: ['inscribe'],
    lore: '谁也没看见它灭，它就一直烧着。' },
  { id: 'blade-25', name: '敛刃', deck: 'blade', tier: 'everburning', cost: 2, type: 'skill', pattern: 'energy',
    text: '造成 8 点伤害。蓄火：本回合未用完的能量保留到下回合。', keywords: ['bank'],
    lore: '把火留在鞘里，下一回合再烧。' },
  { id: 'blade-26', name: '长夜', deck: 'blade', tier: 'everburning', cost: 2, type: 'skill', pattern: 'ramp',
    text: '迟滞：下回合开始时，你获得 3 层余烬，并抽 2 张牌。', keywords: ['delay', 'ember'],
    lore: '夜再长，也长不过胸口的这口气。' },

  // ── 星陨 · starfall ───────────────────────────────────────────── 一副牌只承载得起一枚
  { id: 'blade-27', name: '烬爆', deck: 'blade', tier: 'starfall', cost: 3, type: 'attack', pattern: 'finisher',
    text: '爆燃：获得 3 点能量，下回合开始时少 3 点。消耗你所有余烬，每层造成 3 点伤害。', keywords: ['flare', 'ember'],
    lore: '所有没烧完的，今夜一起烧完。' },
  { id: 'blade-28', name: '千刃', deck: 'blade', tier: 'starfall', cost: 3, type: 'attack', pattern: 'resource-spend',
    text: '消耗你全部锋锐，每层使这张牌多命中 1 次。造成 3 点伤害 3 次。', keywords: ['edge'], bridge: 'bone',
    lore: '一千把刀落下，只需要一个决定。' },
];
