import type { CardDefinition } from './types';

/**
 * 燎原余烬 —— 先铺灼烧让敌人自己烂掉，再把攒下的余烬一把烧成爆发。
 * 滚雪球型：启动最慢、单体直伤最薄、AOE 最密；灼烧垫得越厚，收网那一下越不讲道理。
 */
export const DECK_FLAME: CardDefinition[] = [
  // ── 残烬 · cinder：0~1 费，七张七种形状，各自只做一件事 ────────────────
  { id: 'flame-01', name: '火种', deck: 'flame', tier: 'cinder', cost: 1, type: 'attack', pattern: 'dot-apply',
    text: '造成 4 点伤害，施加 2 层灼烧。', keywords: ['scorch'],
    lore: '留一缕火，照见归途，也照见来路。' },
  { id: 'flame-02', name: '拾柴', deck: 'flame', tier: 'cinder', cost: 1, type: 'skill', pattern: 'block-basic',
    text: '获得 6 点格挡。空明：额外获得 4 点格挡。', keywords: ['empty'],
    lore: '火不挑柴，只挑肯为它弯腰的人。' },
  { id: 'flame-03', name: '引信', deck: 'flame', tier: 'cinder', cost: 0, type: 'attack', pattern: 'multi-hit',
    text: '爆燃：立刻获得 1 点能量。造成 2 点伤害 2 次。', keywords: ['flare'],
    lore: '火沿着一根线跑，不问线的尽头站着谁。' },
  { id: 'flame-04', name: '舔焰', deck: 'flame', tier: 'cinder', cost: 0, type: 'attack', pattern: 'conditional-strike',
    text: '造成 3 点伤害。若目标已被灼烧，额外造成 4 点伤害。', keywords: ['scorch'],
    lore: '它先舔一舔，再决定要不要把人吃掉。' },
  { id: 'flame-05', name: '献薪', deck: 'flame', tier: 'cinder', cost: 0, type: 'skill', pattern: 'sacrifice',
    text: '祭火：失去 4 点生命，对所有敌人施加 2 层灼烧。', keywords: ['sacrifice', 'scorch'],
    lore: '割开手腕的人，才配向火要一个冬天。' },
  { id: 'flame-06', name: '掩薪', deck: 'flame', tier: 'cinder', cost: 1, type: 'skill', pattern: 'resource-build',
    text: '获得 2 层余烬。', keywords: ['ember'], bridge: 'blade',
    lore: '把火埋进灰里，明早它还醒着。' },
  { id: 'flame-07', name: '焦壳', deck: 'flame', tier: 'cinder', cost: 1, type: 'skill', pattern: 'retaliate',
    text: '反震：本回合内每次被攻击时，对攻击者造成 4 点伤害。', keywords: ['retaliate'],
    lore: '烧焦的壳还烫着，谁碰谁留一道印。' },

  // ── 微光 · glimmer：牌组的骨架，灼烧在这里被翻倍、引爆、换成别的东西 ────
  { id: 'flame-08', name: '扬灰', deck: 'flame', tier: 'glimmer', cost: 1, type: 'skill', pattern: 'resource-convert',
    text: '消耗 3 层余烬，对所有敌人施加 2 层灼烧。', keywords: ['ember', 'scorch'],
    lore: '灰扬起来的时候，整片天都是火的后半句。' },
  { id: 'flame-09', name: '裂焰', deck: 'flame', tier: 'glimmer', cost: 1, type: 'attack', pattern: 'dot-convert',
    text: '引爆：消耗目标身上全部灼烧，每层造成 3 点伤害。', keywords: ['detonate', 'scorch'],
    lore: '憋着的那口气一松，焰就裂成了刀。' },
  { id: 'flame-10', name: '浇油', deck: 'flame', tier: 'glimmer', cost: 1, type: 'skill', pattern: 'ramp',
    text: '使目标身上的灼烧层数翻倍。流转：抽 1 张牌。', keywords: ['scorch', 'cycle'],
    lore: '浇下去的不是油，是让它再活一晚的理由。' },
  { id: 'flame-11', name: '伏火', deck: 'flame', tier: 'glimmer', cost: 1, type: 'skill', pattern: 'dot-payoff',
    text: '迟滞：下回合开始时，对所有敌人造成等同于其灼烧层数的伤害。', keywords: ['delay', 'scorch'],
    lore: '今夜看着是熄了，明早却在人骨头里烧。' },
  { id: 'flame-12', name: '存薪', deck: 'flame', tier: 'glimmer', cost: 1, type: 'skill', pattern: 'energy',
    text: '获得 4 点格挡。蓄火：本回合未用完的能量保留到下回合。', keywords: ['bank'],
    lore: '不必一夜烧完，火也懂得过夜。' },
  { id: 'flame-13', name: '回火', deck: 'flame', tier: 'glimmer', cost: 1, type: 'skill', pattern: 'copy',
    text: '对所有敌人施加 1 层灼烧。回响：将这张牌的一个弱化复制品加入手牌。', keywords: ['scorch', 'echo'],
    lore: '回头的火，比头一次更懂得往哪咬。' },
  { id: 'flame-14', name: '余温', deck: 'flame', tier: 'glimmer', cost: 1, type: 'skill', pattern: 'recycle',
    text: '获得 5 点格挡。拾回：从弃牌堆取回一张牌。', keywords: ['reclaim'],
    lore: '火走了，暖还留在灰里等人来取。' },
  { id: 'flame-15', name: '炭衣', deck: 'flame', tier: 'glimmer', cost: 1, type: 'skill', pattern: 'block-convert',
    text: '消耗目标身上至多 4 层灼烧，每层使你获得 3 点格挡。', keywords: ['scorch'], bridge: 'bone',
    lore: '烧成炭的外壳，比新皮更顶得住刀。' },

  // ── 明焰 · blaze：各自有一手绝活的中坚 ────────────────────────────────
  { id: 'flame-16', name: '灰烬雨', deck: 'flame', tier: 'blaze', cost: 2, type: 'skill', pattern: 'dot-apply',
    text: '对所有敌人施加 3 层灼烧。空明：额外施加 2 层。', keywords: ['scorch', 'empty'],
    lore: '烧尽的东西落下来，像一场脏雪。' },
  { id: 'flame-17', name: '焚天', deck: 'flame', tier: 'blaze', cost: 3, type: 'attack', pattern: 'aoe',
    text: '爆燃：立刻获得 2 点能量。消耗全部余烬，每 2 层对所有敌人造成 3 点伤害。', keywords: ['ember', 'flare'], bridge: 'blade',
    lore: '天顶压下来的不是云，是烧红的灰。' },
  { id: 'flame-18', name: '铭火', deck: 'flame', tier: 'blaze', cost: 1, type: 'skill', pattern: 'upgrade',
    text: '刻印：本场战斗永久强化牌组中的一张牌，使其费用减 1。', keywords: ['inscribe'],
    lore: '刻在牌上的火，烧过一次就再不会忘。' },
  { id: 'flame-19', name: '透骨', deck: 'flame', tier: 'blaze', cost: 0, type: 'attack', pattern: 'heavy-strike',
    text: '祭火：失去 8 点生命。对已被灼烧的目标造成 16 点伤害。焚尽。', keywords: ['sacrifice', 'scorch', 'exhaust'],
    lore: '疼到骨头里，才算真的烧着了。' },
  { id: 'flame-20', name: '灼痕', deck: 'flame', tier: 'blaze', cost: 1, type: 'skill', pattern: 'debuff',
    text: '烙印一个敌人：它受到你的攻击牌伤害时，额外受到 3 点伤害，持续 2 回合。', keywords: ['mark'],
    lore: '它记住的不是伤，是那道还没凉的印。' },
  { id: 'flame-21', name: '火墙', deck: 'flame', tier: 'blaze', cost: 2, type: 'skill', pattern: 'block-burst',
    text: '获得 10 点格挡。连缀：若你本回合已打出至少 3 张牌，对所有敌人施加 3 层灼烧。', keywords: ['chain', 'scorch'],
    lore: '墙是火做的，退路也是火做的。' },

  // ── 长明 · everburning：不添柴也能烧下去的引擎 ────────────────────────
  { id: 'flame-22', name: '长明灯', deck: 'flame', tier: 'everburning', cost: 2, type: 'power', pattern: 'ramp',
    text: '每当你施加灼烧时，额外施加 1 层灼烧。', keywords: ['scorch'],
    lore: '灯芯换了三代人，火一次也没换过。' },
  { id: 'flame-23', name: '回炉', deck: 'flame', tier: 'everburning', cost: 1, type: 'skill', pattern: 'recycle',
    text: '返照：把本回合已打出的一张牌退回手牌。若退回的是攻击牌，施加 2 层灼烧。', keywords: ['rewind', 'scorch'],
    lore: '打出去的牌还能捞回来，只要炉子没凉。' },
  { id: 'flame-24', name: '焚炉', deck: 'flame', tier: 'everburning', cost: 2, type: 'attack', pattern: 'resource-spend',
    text: '消耗 4 层余烬，造成 12 点伤害并施加 3 层灼烧。焚尽。', keywords: ['ember', 'scorch', 'exhaust'], bridge: 'blade',
    lore: '把攒下的一切都推进去，只要一个结果。' },
  { id: 'flame-25', name: '骨炭', deck: 'flame', tier: 'everburning', cost: 2, type: 'skill', pattern: 'block-convert',
    text: '移除目标身上全部灼烧，每 2 层使你获得 5 点格挡和 1 层壁垒。', keywords: ['scorch', 'rampart'], bridge: 'bone',
    lore: '烧成炭的骨头，还能再暖一次人。' },
  { id: 'flame-26', name: '蓄炉', deck: 'flame', tier: 'everburning', cost: 1, type: 'power', pattern: 'resource-build',
    text: '蓄火：本回合未用完的能量保留到下回合。每保留 1 点，获得 1 层余烬。', keywords: ['bank', 'ember'],
    lore: '今夜封住炉口，明早火自己会说话。' },

  // ── 星陨 · starfall：一副牌组只承载得起这些 ───────────────────────────
  { id: 'flame-27', name: '燎狱', deck: 'flame', tier: 'starfall', cost: 3, type: 'attack', pattern: 'finisher',
    text: '对所有敌人造成 6 点伤害。目标每有 1 层灼烧，便额外造成 1 点伤害。', keywords: ['scorch'],
    lore: '火大到一定地步，就是地狱的形状。' },
  { id: 'flame-28', name: '恒燃', deck: 'flame', tier: 'starfall', cost: 3, type: 'rite', pattern: 'dot-payoff',
    text: '本场战斗中，敌人身上的灼烧不再随回合消退。', keywords: ['scorch'],
    lore: '它答应过要烧到最后，所以不灭。' },
];
