import type { CardDefinition } from './types';

/**
 * 燎原余烬：先用灼烧把敌人的血线一点点烘下去，再攒余烬，一次性烧成爆发。
 * 滚雪球型 —— 开场最弱，垫得越久越强，对高血量敌人碾压，对快速铺场略吃力。
 */
export const DECK_FLAME: CardDefinition[] = [
  // ── 残烬 cinder：开场那点红，够用，不够赢 ──────────────────────────────
  { id: 'flame-01', name: '火种', deck: 'flame', tier: 'cinder', cost: 1, type: 'attack',
    text: '造成 4 点伤害，施加 2 层灼烧。', keywords: ['scorch'],
    lore: '留一缕火，照见归途，也照见来路。' },
  { id: 'flame-02', name: '拾柴', deck: 'flame', tier: 'cinder', cost: 1, type: 'skill',
    text: '获得 6 点格挡。', keywords: [],
    lore: '火不挑柴，只挑愿意弯腰的人。' },
  { id: 'flame-03', name: '引信', deck: 'flame', tier: 'cinder', cost: 1, type: 'attack',
    text: '造成 6 点伤害。', keywords: [],
    lore: '火沿着一根线跑，不问线的尽头是谁。' },
  { id: 'flame-04', name: '舔焰', deck: 'flame', tier: 'cinder', cost: 0, type: 'attack',
    text: '造成 4 点伤害。', keywords: [],
    lore: '它先舔一舔，再决定要不要吃。' },
  { id: 'flame-05', name: '燃点', deck: 'flame', tier: 'cinder', cost: 1, type: 'skill',
    text: '施加 3 层灼烧。', keywords: ['scorch'],
    lore: '木头记得那个温度，一生都没忘。' },
  { id: 'flame-06', name: '掩薪', deck: 'flame', tier: 'cinder', cost: 1, type: 'skill',
    text: '获得 5 点格挡，获得 1 层余烬。', keywords: ['ember'],
    lore: '把火埋进灰里，明早它还醒着。' },
  { id: 'flame-07', name: '焚风', deck: 'flame', tier: 'cinder', cost: 1, type: 'attack',
    text: '对所有敌人造成 4 点伤害。', keywords: [],
    lore: '风从火场来，带着整片荒原的余味。' },

  // ── 微光 glimmer：牌组的骨架，灼烧与余烬在这里接上 ────────────────────
  { id: 'flame-08', name: '燎原', deck: 'flame', tier: 'glimmer', cost: 2, type: 'attack',
    text: '对所有敌人造成 8 点伤害。', keywords: [],
    lore: '一株草烧起来时，整片原野都在等。' },
  { id: 'flame-09', name: '灰烬雨', deck: 'flame', tier: 'glimmer', cost: 2, type: 'attack',
    text: '对所有敌人施加 3 层灼烧。', keywords: ['scorch'],
    lore: '烧尽的东西落下来，像一场脏雪。' },
  { id: 'flame-10', name: '拢火', deck: 'flame', tier: 'glimmer', cost: 1, type: 'skill',
    text: '获得 2 层余烬。', keywords: ['ember'],
    lore: '把散开的火拢成一堆，它就能过夜。' },
  { id: 'flame-11', name: '焰心', deck: 'flame', tier: 'glimmer', cost: 1, type: 'attack',
    text: '造成 4 点伤害；若目标处于灼烧，额外造成 3 点伤害。', keywords: ['scorch'],
    lore: '焰心是凉的，没人愿意相信。' },
  { id: 'flame-12', name: '焚身', deck: 'flame', tier: 'glimmer', cost: 2, type: 'attack',
    text: '造成目标灼烧层数 ×3 的伤害。', keywords: ['scorch'],
    lore: '烧别人的火，最后总要烧到自己。' },
  { id: 'flame-13', name: '焦壳', deck: 'flame', tier: 'glimmer', cost: 1, type: 'skill',
    text: '获得目标灼烧层数 ×2 的格挡。', keywords: ['scorch'], bridge: 'bone',
    lore: '烧焦的那层壳，比皮肉更懂护人。' },
  { id: 'flame-14', name: '引火', deck: 'flame', tier: 'glimmer', cost: 1, type: 'skill',
    text: '施加 2 层灼烧，获得 1 层余烬。', keywords: ['scorch', 'ember'],
    lore: '借一点火过去，它自己会蔓延。' },
  { id: 'flame-15', name: '爆燃', deck: 'flame', tier: 'glimmer', cost: 1, type: 'attack',
    text: '消耗 1 层余烬，造成 8 点伤害。', keywords: ['ember'], bridge: 'blade',
    lore: '憋久了的东西，一瞬间就全给出来。' },

  // ── 明焰 blaze：各自有一手绝活的中坚 ──────────────────────────────────
  { id: 'flame-16', name: '火墙', deck: 'flame', tier: 'blaze', cost: 2, type: 'skill',
    text: '获得 8 点格挡，对所有敌人施加 2 层灼烧。', keywords: ['scorch'],
    lore: '墙是火做的，退路也是。' },
  { id: 'flame-17', name: '焚天', deck: 'flame', tier: 'blaze', cost: 3, type: 'attack',
    text: '对所有敌人造成 9 点伤害，施加 2 层灼烧。', keywords: ['scorch'],
    lore: '天顶压下来的不是云，是烧红的灰。' },
  { id: 'flame-18', name: '传薪', deck: 'flame', tier: 'blaze', cost: 1, type: 'attack',
    text: '消耗 2 层余烬，造成 10 点伤害。', keywords: ['ember'], bridge: 'blade',
    lore: '薪火递下去，接的人就得接着烧。' },
  { id: 'flame-19', name: '灰蚀', deck: 'flame', tier: 'blaze', cost: 2, type: 'attack',
    text: '造成 7 点伤害，施加 4 层灼烧。', keywords: ['scorch'],
    lore: '灰落在骨头上，慢慢把它啃空。' },
  { id: 'flame-20', name: '炉心', deck: 'flame', tier: 'blaze', cost: 2, type: 'power',
    text: '每回合开始时，对所有敌人施加 1 层灼烧。', keywords: ['scorch'],
    lore: '炉子不问烧什么，只问还有没有。' },
  { id: 'flame-21', name: '透骨', deck: 'flame', tier: 'blaze', cost: 1, type: 'attack',
    text: '造成 4 点伤害，施加 2 层灼烧；若目标已处于灼烧，改为施加 4 层。', keywords: ['scorch'],
    lore: '疼到骨头里，才算真的烧着了。' },

  // ── 长明 everburning：不添柴也能烧下去 ────────────────────────────────
  { id: 'flame-22', name: '长明灯', deck: 'flame', tier: 'everburning', cost: 2, type: 'rite',
    text: '每当你施加灼烧时，额外施加 1 层灼烧。', keywords: ['scorch'],
    lore: '灯芯换了三代人，火没换过。' },
  { id: 'flame-23', name: '烛龙', deck: 'flame', tier: 'everburning', cost: 2, type: 'attack',
    text: '对所有敌人造成 11 点伤害。', keywords: [],
    lore: '它睁眼是白昼，闭眼是长夜。' },
  { id: 'flame-24', name: '焚炉', deck: 'flame', tier: 'everburning', cost: 2, type: 'attack',
    text: '消耗全部余烬，每消耗 1 层造成 3 点伤害。', keywords: ['ember'], bridge: 'blade',
    lore: '把攒下的一切都推进去，只要一个结果。' },
  { id: 'flame-25', name: '积薪', deck: 'flame', tier: 'everburning', cost: 1, type: 'skill',
    text: '获得 3 层余烬。', keywords: ['ember'],
    lore: '柴堆得越高，火越有底气说话。' },
  { id: 'flame-26', name: '骨炭', deck: 'flame', tier: 'everburning', cost: 2, type: 'skill',
    text: '移除目标全部灼烧，每层使你获得 2 点格挡，并获得 2 层壁垒。', keywords: ['scorch', 'rampart'], bridge: 'bone',
    lore: '烧成炭的东西，还能再暖一次人。' },

  // ── 星陨 starfall：一副牌组只承载得起这些 ─────────────────────────────
  { id: 'flame-27', name: '燎狱', deck: 'flame', tier: 'starfall', cost: 3, type: 'attack',
    text: '对所有敌人造成 14 点伤害，施加 4 层灼烧。', keywords: ['scorch'],
    lore: '火大到一定地步，就成了地狱的形状。' },
  { id: 'flame-28', name: '恒燃', deck: 'flame', tier: 'starfall', cost: 3, type: 'rite',
    text: '本场战斗中，敌人身上的灼烧不会随回合消退。', keywords: ['scorch'],
    lore: '它答应过要烧到最后，所以不灭。' },
];
